#
# Copyright (C) 2024 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#


 ## Current Developer Toolbox doesn't support environment files, make sure to remove any files or environment variables starting with $
services:
  ClientGst:
    image: dlstreamer:dev
    deploy:
      mode: replicated
      replicas: ${PIPELINE_COUNT:-1}
    network_mode: "host"
    entrypoint: /home/pipeline-server/entrypoint.sh --pipeline_script_choice ${PIPELINE_SCRIPT:-run-pipeline.sh}
    privileged: true
    ipc: "host"
    env_file:
      - .env
      - ${DEVICE_ENV:-res/all-cpu.env}
    environment:
      - CONTAINER_NAME=${CONTAINER_NAME}
      - RTSP_OUTPUT=${RTSP_OUTPUT}
      - RENDER_MODE=${RENDER_MODE}
    volumes:
      - ${RESULTS_DIR:-../results}:/tmp/results
      - ~/.Xauthority:/home/dlstreamer/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.cl-cache:/home/pipeline-server/.cl-cache
      - ./res/:/home/pipeline-server/envs
      - ${RETAIL_USE_CASE_ROOT:-}/models:/home/pipeline-server/models
      - ../config/sample-videos/qsr-usecase.mp4:/sample-videos/
    restart: on-failure  