name: Integration Tests

# Runs on every pr pushed
on: 
#   push:
#     branches: [ "main" ]
    pull_request_target:
    # The branches below must be a subset of the branches above
        branches: [ "main" ]

# Runs on schedule at 9am UTC, Monday to Friday everyday
#on:
#  schedule:
#    - cron: '0 9 * * 1-5'

permissions:
  contents: read

jobs:
  run_integration_tests:
      runs-on: [ubuntu-latest]
      steps:
          - name: Cleanup repo build folder
            run: |
              ls -la ./
              sudo rm -rf ./* || true
              sudo rm -rf ./.??* || true
              ls -la ./
          - name: Checkout code
            uses: actions/checkout@v4
          - name: run integration tests
            run: |
              make run-smoke-tests
          - name: success
            if: success()
            run: |
              echo "Tests are successful"
          - name: failure
            if: failure()
            run: |
              echo "Tests have failed"